-- Add extended passport and address fields to customers table

SET @col1 = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'customers' AND COLUMN_NAME = 'passport_issued');
SET @sql1 = IF(@col1 = 0, 'ALTER TABLE customers ADD COLUMN passport_issued VARCHAR(500) NULL AFTER passport_number', 'SELECT 1');
PREPARE stmt1 FROM @sql1; EXECUTE stmt1; DEALLOCATE PREPARE stmt1;

SET @col2 = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'customers' AND COLUMN_NAME = 'passport_date');
SET @sql2 = IF(@col2 = 0, 'ALTER TABLE customers ADD COLUMN passport_date VARCHAR(20) NULL AFTER passport_issued', 'SELECT 1');
PREPARE stmt2 FROM @sql2; EXECUTE stmt2; DEALLOCATE PREPARE stmt2;

SET @col3 = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'customers' AND COLUMN_NAME = 'passport_code');
SET @sql3 = IF(@col3 = 0, 'ALTER TABLE customers ADD COLUMN passport_code VARCHAR(10) NULL AFTER passport_date', 'SELECT 1');
PREPARE stmt3 FROM @sql3; EXECUTE stmt3; DEALLOCATE PREPARE stmt3;

SET @col4 = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'customers' AND COLUMN_NAME = 'birth_date');
SET @sql4 = IF(@col4 = 0, 'ALTER TABLE customers ADD COLUMN birth_date VARCHAR(20) NULL AFTER passport_code', 'SELECT 1');
PREPARE stmt4 FROM @sql4; EXECUTE stmt4; DEALLOCATE PREPARE stmt4;

SET @col5 = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'customers' AND COLUMN_NAME = 'birth_place');
SET @sql5 = IF(@col5 = 0, 'ALTER TABLE customers ADD COLUMN birth_place VARCHAR(500) NULL AFTER birth_date', 'SELECT 1');
PREPARE stmt5 FROM @sql5; EXECUTE stmt5; DEALLOCATE PREPARE stmt5;

SET @col6 = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'customers' AND COLUMN_NAME = 'registration_address');
SET @sql6 = IF(@col6 = 0, 'ALTER TABLE customers ADD COLUMN registration_address TEXT NULL AFTER birth_place', 'SELECT 1');
PREPARE stmt6 FROM @sql6; EXECUTE stmt6; DEALLOCATE PREPARE stmt6;

-- Company extended fields
SET @col7 = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'customers' AND COLUMN_NAME = 'kpp');
SET @sql7 = IF(@col7 = 0, 'ALTER TABLE customers ADD COLUMN kpp VARCHAR(20) NULL AFTER ogrn', 'SELECT 1');
PREPARE stmt7 FROM @sql7; EXECUTE stmt7; DEALLOCATE PREPARE stmt7;

SET @col8 = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'customers' AND COLUMN_NAME = 'bank_name');
SET @sql8 = IF(@col8 = 0, 'ALTER TABLE customers ADD COLUMN bank_name VARCHAR(255) NULL AFTER kpp', 'SELECT 1');
PREPARE stmt8 FROM @sql8; EXECUTE stmt8; DEALLOCATE PREPARE stmt8;

SET @col9 = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'customers' AND COLUMN_NAME = 'bik');
SET @sql9 = IF(@col9 = 0, 'ALTER TABLE customers ADD COLUMN bik VARCHAR(20) NULL AFTER bank_name', 'SELECT 1');
PREPARE stmt9 FROM @sql9; EXECUTE stmt9; DEALLOCATE PREPARE stmt9;

SET @col10 = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'customers' AND COLUMN_NAME = 'checking_account');
SET @sql10 = IF(@col10 = 0, 'ALTER TABLE customers ADD COLUMN checking_account VARCHAR(30) NULL AFTER bik', 'SELECT 1');
PREPARE stmt10 FROM @sql10; EXECUTE stmt10; DEALLOCATE PREPARE stmt10;

SET @col11 = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'customers' AND COLUMN_NAME = 'corr_account');
SET @sql11 = IF(@col11 = 0, 'ALTER TABLE customers ADD COLUMN corr_account VARCHAR(30) NULL AFTER checking_account', 'SELECT 1');
PREPARE stmt11 FROM @sql11; EXECUTE stmt11; DEALLOCATE PREPARE stmt11;

SET @col12 = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'customers' AND COLUMN_NAME = 'legal_address');
SET @sql12 = IF(@col12 = 0, 'ALTER TABLE customers ADD COLUMN legal_address TEXT NULL AFTER corr_account', 'SELECT 1');
PREPARE stmt12 FROM @sql12; EXECUTE stmt12; DEALLOCATE PREPARE stmt12;

SET @col13 = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'customers' AND COLUMN_NAME = 'contact_person_email');
SET @sql13 = IF(@col13 = 0, 'ALTER TABLE customers ADD COLUMN contact_person_email VARCHAR(255) NULL AFTER contact_person', 'SELECT 1');
PREPARE stmt13 FROM @sql13; EXECUTE stmt13; DEALLOCATE PREPARE stmt13;

SET @col14 = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'customers' AND COLUMN_NAME = 'contact_person_phone');
SET @sql14 = IF(@col14 = 0, 'ALTER TABLE customers ADD COLUMN contact_person_phone VARCHAR(30) NULL AFTER contact_person_email', 'SELECT 1');
PREPARE stmt14 FROM @sql14; EXECUTE stmt14; DEALLOCATE PREPARE stmt14;
